version: '3.8'
services:
  client:
    build: 
      context: ./front/synergief
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  server:
    build:
      context: ./back/synergieb
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
